version: '3.8'
services:
  server:
    build: .
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql_net

  client:
    image: mysql:8.0.23
    depends_on: 
      - server
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql_net

networks:
  mysql_net:
