version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    networks:
      - study_net
    volumes:
      - /dev/shm:/dev/shm
  
  web:
    image: nginx
    expose: 
      - 80
    networks:
      - study_net

networks:
  study_net:
