version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome
    expose:
      - 4444
    networks:
      - study_net
    volumes:
      - /dev/shm:/dev/shm
  
  web:
    image: nginx
    expose: 
      - 80
    networks:
      - study_net

  notebook:
    build:
      context: .
      dockerfile: Dockerfile-notebook
    depends_on: 
      - selenium
    volumes:
      - ./volumes/notebook:/home/jovyan/work
    ports:
      - 8888:8888
    networks:
      - study_net

networks:
  study_net:
